---
  - name: My first playbook
    hosts: webservers
    become: true
    tasks:

    - name: Update docker.io  (state=present is optional)
      apt:
        name: docker.io
        state: present
    - name: Install python3-pip  (state=present is optional)
      apt:
        name: python3-pip
        state: present
    - name: Install docker via pip  (state=present is optional)
      pip:
        name: docker
        state: present

    - name: Install dvwa via docker-container  (state=present is optional)
      community.docker.docker_container:
        name: dvwainstall
        image: cyberxsecurity/dvwa
        restart_policy: always
        published_ports: 80:80
        state: started


    - name: Start docker when vm starts  (state=present is optional)
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

